spring:

  application:
    name: url-shortener

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:h2:mem:url_db
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true
